name: flutter_readium
description: A Flutter wrapper for Readium swift-toolkit and kotlin-toolkit.
version: 0.0.1
homepage: https://github.com/Notalib/flutter_readium
# TODO: this is here to enable path: dependencies for now.
# Will need to be removed once actually publishing the plugin.
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service:
    git:
      url: git@github.com:Notalib/audio_service.git
      ref: lyt
      path: audio_service
  audio_session:
  background_downloader: 8.5.4 # 8.5.5 introduces a bug that prevents our downloads from finishing properly
  collection:
  connectivity_plus:
  dio:
  flutter_lints:
  flutter_tts:
  freezed_annotation:
  json_annotation: ^4.9.0
  json_diff:
  just_audio:
    git:
      url: git@github.com:notalib/just_audio.git
      ref: lyt4
      path: just_audio
  path: ^1.9.0
  path_provider:
  rxdart:
  stream_transform:
  wakelock_plus: ^1.2.8
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:
  lint:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# Commented out because of https://github.com/flutter/flutter-intellij/issues/5596
# Uncommented back in, since commenting it out silently breaks opening e-books.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: R2NavigatorFlutterPlugin
      android:
        package: dk.nota.flutter_readium
        pluginClass: R2NavigatorFlutterPlugin
  assets:
    - assets/helpers/
